server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # You can adjust this value based on your needs
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update  # You can change this to 'none', 'update', 'create', 'create-drop' based on your needs
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
